2021-12-12 11:51:46,297 Downloading and reading the exported model
wandb: ERROR Project samico/udacity_airbnb does not contain artifact: "clean_sample.csv:latest"
Traceback (most recent call last):
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project samico/udacity_airbnb does not contain artifact: "clean_sample.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 319, in <module>
    go(args)
  File "run.py", line 58, in go
    trainval_local_path = run.use_artifact(args.trainval_artifact).file()
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/opt/conda/envs/mlflow-cd3b4f52f7dead4ede9554d420a1b9da8d8db1e3/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project samico/udacity_airbnb does not contain artifact: "clean_sample.csv:latest"
